### ISSUE TITLE
Error at running the script

### ISSUE THREAD

**Issue by c0de51** [rzc0d3r/CPU-Voltage-Control#2]
I got this error when I run it. ![Screenshot_2024-03-02-21-52-59-217_ru.iiec.pydroid3.jpg](https://github.com/rzc0d3r/CPU-Voltage-Control/assets/161986458/0f37ed47-6b5d-49aa-95f0-b23b082ae6c8)

Device: POCO X6 Pro

**Comment by rzc0d3r** [comment]
Try to find in /proc или в корне памяти / the folders EEM_DET_L, EEM_DET_B, EEM_DET_CCI, EEM_DET_GPU and so on. Where there is a note EEM_DET_

It's just that each device has different kernel settings. Also look for a file named eem_offset

**Comment by c0de51** [comment]
> Try to find in ```/proc``` or ```/``` the folders: ```EEM_DET_L```
> ```EEM_DET_B```
> ```EEM_DET_CCI```
> ```EEM_DET_GPU```
> 
> and so on where there is a note ```EEM_DET_```
> 
> It's just that each device has different kernel settings. Also look for a file named ```eem_offset```

Hello, thanks for the reply.

I searched all the folders and files name at root explorer and found nothing.

The poco x6 pro uses gki kernel.
